"""autogenerated by genpy from dmp_execute/PolicyImprovementStatistics.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PolicyImprovementStatistics(genpy.Message):
  _md5sum = "415c0d797d401ff1a37056c27e83e972"
  _type = "dmp_execute/PolicyImprovementStatistics"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 iteration
float64[] rollout_costs
float64 noiseless_cost

"""
  __slots__ = ['iteration','rollout_costs','noiseless_cost']
  _slot_types = ['int32','float64[]','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       iteration,rollout_costs,noiseless_cost

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PolicyImprovementStatistics, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.iteration is None:
        self.iteration = 0
      if self.rollout_costs is None:
        self.rollout_costs = []
      if self.noiseless_cost is None:
        self.noiseless_cost = 0.
    else:
      self.iteration = 0
      self.rollout_costs = []
      self.noiseless_cost = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_i.pack(self.iteration))
      length = len(self.rollout_costs)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.rollout_costs))
      buff.write(_struct_d.pack(self.noiseless_cost))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (self.iteration,) = _struct_i.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.rollout_costs = struct.unpack(pattern, str[start:end])
      start = end
      end += 8
      (self.noiseless_cost,) = _struct_d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_i.pack(self.iteration))
      length = len(self.rollout_costs)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.rollout_costs.tostring())
      buff.write(_struct_d.pack(self.noiseless_cost))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (self.iteration,) = _struct_i.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.rollout_costs = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 8
      (self.noiseless_cost,) = _struct_d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_i = struct.Struct("<i")
_struct_d = struct.Struct("<d")
