/* Auto-generated by genmsg_cpp for file /home/lluis/catkin_ws/src/usc-clmc-ros-pkg/dmp/dynamic_movement_primitive/msg/StateMsg.msg */
#ifndef DYNAMIC_MOVEMENT_PRIMITIVE_MESSAGE_STATEMSG_H
#define DYNAMIC_MOVEMENT_PRIMITIVE_MESSAGE_STATEMSG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace dynamic_movement_primitive
{
template <class ContainerAllocator>
struct StateMsg_ {
  typedef StateMsg_<ContainerAllocator> Type;

  StateMsg_()
  : x(0.0)
  , xd(0.0)
  , xdd(0.0)
  {
  }

  StateMsg_(const ContainerAllocator& _alloc)
  : x(0.0)
  , xd(0.0)
  , xdd(0.0)
  {
  }

  typedef double _x_type;
  double x;

  typedef double _xd_type;
  double xd;

  typedef double _xdd_type;
  double xdd;


  typedef boost::shared_ptr< ::dynamic_movement_primitive::StateMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamic_movement_primitive::StateMsg_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct StateMsg
typedef  ::dynamic_movement_primitive::StateMsg_<std::allocator<void> > StateMsg;

typedef boost::shared_ptr< ::dynamic_movement_primitive::StateMsg> StateMsgPtr;
typedef boost::shared_ptr< ::dynamic_movement_primitive::StateMsg const> StateMsgConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::dynamic_movement_primitive::StateMsg_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::dynamic_movement_primitive::StateMsg_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace dynamic_movement_primitive

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::dynamic_movement_primitive::StateMsg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::dynamic_movement_primitive::StateMsg_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::dynamic_movement_primitive::StateMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "42a392db9f28d01056ff8131374306ce";
  }

  static const char* value(const  ::dynamic_movement_primitive::StateMsg_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x42a392db9f28d010ULL;
  static const uint64_t static_value2 = 0x56ff8131374306ceULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamic_movement_primitive::StateMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dynamic_movement_primitive/StateMsg";
  }

  static const char* value(const  ::dynamic_movement_primitive::StateMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::dynamic_movement_primitive::StateMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 x\n\
float64 xd\n\
float64 xdd\n\
\n\
";
  }

  static const char* value(const  ::dynamic_movement_primitive::StateMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::dynamic_movement_primitive::StateMsg_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::dynamic_movement_primitive::StateMsg_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.xd);
    stream.next(m.xdd);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct StateMsg_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamic_movement_primitive::StateMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::dynamic_movement_primitive::StateMsg_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "xd: ";
    Printer<double>::stream(s, indent + "  ", v.xd);
    s << indent << "xdd: ";
    Printer<double>::stream(s, indent + "  ", v.xdd);
  }
};


} // namespace message_operations
} // namespace ros

#endif // DYNAMIC_MOVEMENT_PRIMITIVE_MESSAGE_STATEMSG_H

